version: "3.3"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./db.sqlite:/code/db.sqlite
    ports:
      - "8000:8000"

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/code
