# Generated by Django 3.2.5 on 2021-07-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='user_id',
            new_name='username',
        ),
    ]
