# Generated by Django 3.2.5 on 2021-07-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210727_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='username',
            new_name='user_id',
        ),
    ]
