# Generated by Django 3.2.5 on 2021-07-27 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210727_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='quota',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
