# Generated by Django 3.2.5 on 2021-07-27 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210727_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='quota',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(9223372036854775807)]),
        ),
    ]
